package com.spring_app.sandbox.service.impl;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.springframework.data.domain.Sort;
import org.springframework.data.domain.Sort.Direction;
import org.springframework.stereotype.Service;

import com.spring_app.sandbox.domain.CreateTaskRequest;
import com.spring_app.sandbox.domain.UpdateTaskRequest;
import com.spring_app.sandbox.domain.entity.Task;
import com.spring_app.sandbox.domain.entity.TaskStatus;
import com.spring_app.sandbox.exception.TaskNotFoundException;
import com.spring_app.sandbox.repository.TaskRepository;
import com.spring_app.sandbox.service.TaskService;

@Service // Marks as a bean and injects dependecies we declare in the constructor
// and also indicates that this class is a service component in the Spring context
public class TaskServiceImpl implements TaskService {

    private final TaskRepository taskRepository;

    // argument is dependecy that we want Spring to inject for us, and we declare it as final to indicate that it should not be changed after construction  
    public TaskServiceImpl(TaskRepository taskRepository) {
        this.taskRepository = taskRepository;
    }

    @Override
    public Task createTask(CreateTaskRequest request) {
        // Implementation for creating a task
        Instant now = Instant.now();
        Task task = new Task(
            null, // id will be generated by the database
            request.title(),
            request.description(),
            request.dueDate(),
            TaskStatus.OPEN, // default status for new tasks
            request.priority(),
            now,
            now
        );
        return taskRepository.save(task); // save the task to the database and return the saved entity (with generated id)  (this method returns the task)
    }

    @Override
    public Task updateTask(UUID taskID, UpdateTaskRequest request) {

        Task task = taskRepository.findById(taskID)
            .orElseThrow(() -> new TaskNotFoundException(taskID)); // if task with the given id is not found, throw a TaskNotFoundException
        
        task.setTitle(request.title());
        task.setDescription(request.description());
        task.setDueDate(request.dueDate());
        task.setStatus(request.status());
        task.setPriority(request.priority());
        task.setUpdated(Instant.now()); // update the updated timestamp to now

        // TODO: Add @Transactional and optimistic locking (@Version) for production-grade concurrency control
        return taskRepository.save(task);
    }
    
    @Override
    public List<Task> listTasks() {
        return taskRepository.findAll(Sort.by(Direction.ASC, "created")); // find all tasks sorted by created timestamp ascending
    }

}
